// Data staff & mapping dresscode per divisi — BEM ITS Kabinet Titik Bangkit
const DRESSCODE_MAP = {
  "MEDSI": {
    nama: "Multimedia & Informasi",
    color: "Putih",
    hex: "#FFFFFF",
    textColor: "#1A1A1A",
    border: "#D8D8D8",
  },
  "AKSPRO": {
    nama: "Aksi & Propaganda",
    color: "Hitam",
    hex: "#1A1A1A",
    textColor: "#FFFFFF",
  },
  "KP": {
    nama: "Kebijakan Publik",
    color: "Hitam",
    hex: "#1A1A1A",
    textColor: "#FFFFFF",
  },
  "AIK": {
    nama: "Advokasi Isu Kampus",
    color: "Hitam",
    hex: "#1A1A1A",
    textColor: "#FFFFFF",
  },
  "SOSMAS": {
    nama: "Sosial Masyarakat",
    color: "Cream",
    hex: "#F1E3C8",
    textColor: "#6B5B3D",
  },
  "LHK": {
    nama: "Lingkungan Hidup & Kebencanaan",
    color: "Cream",
    hex: "#F1E3C8",
    textColor: "#6B5B3D",
  },
  "DAGRI": {
    nama: "Dalam Negeri",
    color: "Coklat",
    hex: "#6F4E37",
    textColor: "#FFFFFF",
  },
  "LUGRI": {
    nama: "Luar Negeri",
    color: "Coklat",
    hex: "#6F4E37",
    textColor: "#FFFFFF",
  },
  "KESMA": {
    nama: "Kesejahteraan Mahasiswa",
    color: "Coklat",
    hex: "#6F4E37",
    textColor: "#FFFFFF",
  },
  "PSDM": {
    nama: "Pengembangan Sumber Daya Mahasiswa",
    color: "Biru",
    hex: "#2E5FA8",
    textColor: "#FFFFFF",
  },
  "RISTEK": {
    nama: "Riset & Teknologi",
    color: "Biru",
    hex: "#2E5FA8",
    textColor: "#FFFFFF",
  },
};

const STAFF_DATA = [
  { "nama": "Nayla Aisha Hanifa", "divisiKode": "MEDSI" },
  { "nama": "Nuha Usama Okbah", "divisiKode": "MEDSI" },
  { "nama": "Nabillah Julia Rizqy", "divisiKode": "MEDSI" },
  { "nama": "Maulana Ikhsan", "divisiKode": "MEDSI" },
  { "nama": "Imelda Putri Efendi", "divisiKode": "MEDSI" },
  { "nama": "Muhammad Salman Rifki Haq", "divisiKode": "AIK" },
  { "nama": "Raissa Omar Zhafif", "divisiKode": "AIK" },
  { "nama": "Happy Tahtakisariyyan Mastwaya", "divisiKode": "AIK" },
  { "nama": "Muhammad Salman Dzaki Haq", "divisiKode": "AIK" },
  { "nama": "Faizatul Hidayah", "divisiKode": "AKSPRO" },
  { "nama": "Ratu Aisyah Carenina Marchella Ananta", "divisiKode": "AKSPRO" },
  { "nama": "Tsabitah Pramesti Maharani Putri Adikara", "divisiKode": "AKSPRO" },
  { "nama": "Maslanda Abdi Nugraha", "divisiKode": "AKSPRO" },
  { "nama": "Derryell Josua Ekklesio Pandiangan", "divisiKode": "AKSPRO" },
  { "nama": "Salva Nur Afisita", "divisiKode": "AKSPRO" },
  { "nama": "Jonatan Pebrianto Purba", "divisiKode": "AKSPRO" },
  { "nama": "Gigih Ahmad Pramana", "divisiKode": "AKSPRO" },
  { "nama": "Agung Dwi Prasetyo Adhi Wijaya", "divisiKode": "AKSPRO" },
  { "nama": "Hardiansyah Eka Prasetyo", "divisiKode": "DAGRI" },
  { "nama": "Rama Aulia Sucipta", "divisiKode": "DAGRI" },
  { "nama": "Ahmad Sibawaihi", "divisiKode": "DAGRI" },
  { "nama": "Rama Akbar Suwitoputra", "divisiKode": "DAGRI" },
  { "nama": "Nayla Salsabila Sujarwanto", "divisiKode": "DAGRI" },
  { "nama": "Alief Britama Purnomo", "divisiKode": "DAGRI" },
  { "nama": "M Fa'iq Athallah", "divisiKode": "DAGRI" },
  { "nama": "Muhammad Nafis Abdul Majid", "divisiKode": "DAGRI" },
  { "nama": "Raffi Ananda Pratama", "divisiKode": "KP" },
  { "nama": "Aryaguna Nurjatmiko", "divisiKode": "KP" },
  { "nama": "Muhammad Iqbal Fikri", "divisiKode": "KP" },
  { "nama": "Wildan Evan Saputra", "divisiKode": "KP" },
  { "nama": "Nadya Pramesthi Putri", "divisiKode": "KP" },
  { "nama": "Muhammad Nadhif Alamshah", "divisiKode": "KP" },
  { "nama": "Apri Winner Girsang", "divisiKode": "KP" },
  { "nama": "Lutfi Arrasyidurrahman", "divisiKode": "KP" },
  { "nama": "Ajeng Ayu Syaputri", "divisiKode": "KESMA" },
  { "nama": "Masykuri Abdurrahman", "divisiKode": "KESMA" },
  { "nama": "Hannan Alfi Abdul Yasya", "divisiKode": "KESMA" },
  { "nama": "Fatan Dzunnur Rachman Alfaruqy", "divisiKode": "LHK" },
  { "nama": "bilqis aulia datu munawaroh", "divisiKode": "LHK" },
  { "nama": "Propa Pramodha Wardani", "divisiKode": "LHK" },
  { "nama": "Luna Aulia Afifah", "divisiKode": "LHK" },
  { "nama": "Ahmad Hasan", "divisiKode": "LHK" },
  { "nama": "Lusiana Lukmitta Joethi", "divisiKode": "LHK" },
  { "nama": "Muhammad Fatih Azizi", "divisiKode": "LHK" },
  { "nama": "Aslam romero siregar", "divisiKode": "LHK" },
  { "nama": "Jeco Giovani", "divisiKode": "LHK" },
  { "nama": "Muhammad Khosyi Syehab", "divisiKode": "LHK" },
  { "nama": "Muhammad Haidar Hariri", "divisiKode": "LHK" },
  { "nama": "Bintang Panggau", "divisiKode": "LUGRI" },
  { "nama": "Made Aditya Sunu Ghosa", "divisiKode": "LUGRI" },
  { "nama": "Ahmad Muzakkiy", "divisiKode": "LUGRI" },
  { "nama": "Mohammad Najib Bahrudin", "divisiKode": "LUGRI" },
  { "nama": "Calvin Jusuf Firoos Effendy", "divisiKode": "LUGRI" },
  { "nama": "Khanza Fairuz Aisy", "divisiKode": "LUGRI" },
  { "nama": "Allessandra Najwa Neysaprada", "divisiKode": "PSDM" },
  { "nama": "Nikita Cavalera H", "divisiKode": "PSDM" },
  { "nama": "Azizah Muthiah Aini", "divisiKode": "PSDM" },
  { "nama": "Siti Nur Aisyah", "divisiKode": "RISTEK" },
  { "nama": "Berliana Ayu Anda Lusia", "divisiKode": "RISTEK" },
  { "nama": "Irwan Maulana", "divisiKode": "RISTEK" },
  { "nama": "Adji Wahyudi", "divisiKode": "RISTEK" },
  { "nama": "Dionisius Junio Widayanto", "divisiKode": "RISTEK" },
  { "nama": "Kresna Bayu", "divisiKode": "RISTEK" },
  { "nama": "Ahmad Rafi Maulana Al Ayyubi", "divisiKode": "RISTEK" },
  { "nama": "ACHMAD ZILDAN ARDIANSYAH", "divisiKode": "RISTEK" },
  { "nama": "Iqbal Rizki Muhammad Fadhli", "divisiKode": "RISTEK" },
  { "nama": "Haris Tsuraih", "divisiKode": "SOSMAS" },
  { "nama": "Nicolas Andrean", "divisiKode": "SOSMAS" },
  { "nama": "Husnia Umaro", "divisiKode": "SOSMAS" },
  { "nama": "Qouwy Ar’raukhilla Koesmanto", "divisiKode": "SOSMAS" },
  { "nama": "Syifa Nur Khalisa", "divisiKode": "SOSMAS" },
  { "nama": "Adi Setiawan", "divisiKode": "SOSMAS" },
  { "nama": "Safratul Ulyaa Zahari", "divisiKode": "SOSMAS" },
  { "nama": "Raka Ardi Wiguna", "divisiKode": "SOSMAS" },
  { "nama": "Muhammad Farrel Ardan Zamroniansyah", "divisiKode": "SOSMAS" },
  { "nama": "Muhamat Aril Setiawan", "divisiKode": "SOSMAS" },
  { "nama": "Satria Wahyu Widiatama", "divisiKode": "SOSMAS" },
  { "nama": "Ferlin Erdina Sari", "divisiKode": "SOSMAS" },
  { "nama": "Wuli Silan Midzkar", "divisiKode": "SOSMAS" },
];
